In [4]:
y_actual = [20, 30, 40, 50, 60]
y_pred = [20.5, 30.3, 40.2, 50.6, 60.7]

n = len(y_actual)
mae = sum(abs(ya - yp) for ya, yp in zip(y_actual, y_pred)) / n
mse = sum((ya - yp) ** 2 for ya, yp in zip(y_actual, y_pred)) / n
rmse = mse ** 0.5

print("Mean Absolute Error (MAE):", mae)
print("Mean Squared Error (MSE):", mse)
print("Root Mean Squared Error (RMSE):", rmse)

import numpy as np

y_actual = np.array([20, 30, 40, 50, 60])
y_pred = np.array([20.5, 30.3, 40.2, 50.6, 60.7])

mae = np.mean(np.abs(y_actual - y_pred))
mse = np.mean((y_actual - y_pred) ** 2)
rmse = np.sqrt(mse)
print("Mean Absolute Error:", mae)
print("Mean Squared Error:", mse)
print("Root Mean Squared Error:", rmse)

from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
y_actual = [0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2]
y_pred = [0, 0, 1, 2, 2, 1, 0, 2, 0, 2, 0, 0, 1, 2, 2]

cm = confusion_matrix(y_actual, y_pred)
print("Confusion Matrix:")
print(cm)

accuracy = accuracy_score(y_actual, y_pred)
precision = precision_score(y_actual, y_pred, average='weighted')
recall = recall_score(y_actual, y_pred, average='weighted')
f1 = f1_score(y_actual, y_pred, average='weighted')

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)



Mean Absolute Error (MAE): 0.4600000000000016
Mean Squared Error (MSE): 0.24600000000000147
Root Mean Squared Error (RMSE): 0.49598387070549127
Mean Absolute Error: 0.4600000000000016
Mean Squared Error: 0.24600000000000147
Root Mean Squared Error: 0.49598387070549127
Confusion Matrix:
[[2 1 2]
 [2 1 2]
 [2 1 2]]
Accuracy: 0.3333333333333333
Precision: 0.3333333333333333
Recall: 0.3333333333333333
F1 Score: 0.3257575757575758
